version: '3.8'
services:
  web:
    container_name: logistics_app
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py create_database &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - .env.dev
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: user_0
      POSTGRES_PASSWORD: password_0
      POSTGRES_DB: logistics_db
    ports:
      - 5432:5432

volumes:
  postgres_data:
